core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('account.urls')),
    path('', include('dashboard.urls')),
    path('', include('lead.urls')),
    path('', include('client.urls')),
    path('', include('team.urls')),
]

lead/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('leads-list/', views.leads_list, name='leads_list'),
    path('view-lead/<int:pk>', views.view_lead, name='view_lead'),
    path('add-lead/', views.add_lead, name='add_lead'),
    path('delete-lead/<int:pk>', views.delete_lead, name='delete_lead'),
    path('update-lead/<int:pk>', views.update_lead, name='update_lead'),
    path('convert-to-client/<int:pk>', views.convert_to_client, name='convert_to_client'),
    path('contact-lead/<int:pk>', views.contact_lead, name='contact_lead'),
]

lead/models.py
from django.db import models
from django.contrib.auth import get_user_model
from team.models import Team
User = get_user_model()

# Create your models here.
class Lead(models.Model):
    LOW = 'Low'
    MEDIUM = 'medium'
    HIGH = 'high'

    PRIORITY_CHOICES = (
        (LOW, 'Low'),
        (MEDIUM, 'Medium'),
        (HIGH, 'High')
    )

    NEW = 'New'
    CONTACTED = 'Contacted'
    WON = 'Won'
    LOST = 'Lost'

    STATUS_CHOICES = (
        (NEW, 'New'),
        (CONTACTED, 'Contacted'),
        (WON, 'Won'),
        (LOST, 'Lost'),
    )

    name = models.CharField(max_length=255)
    email = models.EmailField()
    description = models.TextField(blank=True, null=True)
    team = models.ForeignKey(Team, on_delete=models.SET_NULL, null=True, blank=True)
    priority = models.CharField(max_length=10, choices=PRIORITY_CHOICES, default=MEDIUM)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default=NEW)
    converted_to_client = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='leads', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    
class Comment(models.Model):
    content = models.TextField(blank=True, null=True) 
    team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='lead_comments', null=True, blank=True)
    lead = models.ForeignKey(Lead, on_delete=models.CASCADE, null=True, blank=True)
    created_by = models.ForeignKey(User, related_name='lead_comments', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.created_by

class Contact(models.Model):
    subject = models.CharField(max_length=1000)
    content = models.TextField(blank=True, null=True) 

    def __str__(self):
        return self.subject


    

lead/forms.py
from django import forms
from .models import Lead, Comment, Contact

class AddLeadForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = ('name', 'email', 'description', 'priority', 'status',)

    def __init__(self, *args, **kwargs):
        super(AddLeadForm, self).__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['name'].widget.attrs['placeholder'] = 'name'
        self.fields['name'].label = ''

        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'email'
        self.fields['email'].label = ''

        self.fields['description'].widget.attrs['class'] = 'form-control'
        self.fields['description'].widget.attrs['placeholder'] = 'description'
        self.fields['description'].widget.attrs['rows'] = 3
        self.fields['description'].label = ''

        self.fields['priority'].widget.attrs['class'] = 'form-control'
        self.fields['priority'].widget.attrs['placeholder'] = 'priority'
        self.fields['priority'].label = ''

        self.fields['status'].widget.attrs['class'] = 'form-control'
        self.fields['status'].widget.attrs['placeholder'] = 'status'
        self.fields['status'].label = ''

class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

    def __init__(self, *args, **kwargs):
        super(AddCommentForm, self).__init__(*args, **kwargs)

        self.fields['content'].widget.attrs['class'] = 'form-control'
        self.fields['content'].widget.attrs['placeholder'] = 'comment'
        self.fields['content'].widget.attrs['rows'] = 2
        self.fields['content'].label = ''


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('subject', 'content', )

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)

        self.fields['subject'].widget.attrs['class'] = 'form-control'
        self.fields['subject'].widget.attrs['placeholder'] = 'subject'
        self.fields['subject'].label = ''

        self.fields['content'].widget.attrs['class'] = 'form-control'
        self.fields['content'].widget.attrs['placeholder'] = 'content'
        self.fields['content'].widget.attrs['rows'] = 6
        self.fields['content'].label = ''

lead/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import AddLeadForm, AddCommentForm, ContactForm
from .models import Lead, Comment, Contact
from account.models import Account
from client.models import Client
from team.models import Team
from django.core.mail import send_mail
from django.conf import settings

# Create your views here.
@login_required
def leads_list(request):
    leads = Lead.objects.filter(created_by=request.user, converted_to_client=False)
    return render(request, 'lead/leads_list.html', {'leads':leads})

@login_required
def view_lead(request, pk):
    lead = get_object_or_404(Lead, pk=pk)
    team = lead.team
    comments = Comment.objects.filter(team=team)
    if request.method == "POST":
        form = AddCommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.created_by = request.user
            comment.lead = lead
            comment.team = lead.team
            comment.save()
            messages.success(request, "Successfully added comment")
            return redirect('dashboard')
    else:
        form = AddCommentForm()
    return render(request, 'lead/view_lead.html', {'lead':lead, 'comments':comments, 'form':form})

@login_required
def add_lead(request):
    if request.method == "POST":
        form = AddLeadForm(request.POST)
        if form.is_valid():
            lead = form.save(commit=False)
            lead.created_by = request.user
            acc = get_object_or_404(Account, user=request.user)
            lead.team = acc.team
            lead.save()
            messages.success(request, "Successfully created lead")
            return redirect('leads_list')
    else:
        form = AddLeadForm()
    return render(request, 'lead/add_lead.html', {'form':form})

@login_required
def delete_lead(request, pk):
    lead = get_object_or_404(Lead, created_by=request.user, pk=pk)
    lead.delete()
    messages.success(request, "Successfully deleted lead")
    return redirect('leads_list')

@login_required
def update_lead(request, pk):
    lead = get_object_or_404(Lead, created_by=request.user, pk=pk)
    if request.method == "POST":
        form = AddLeadForm(request.POST, instance=lead)
        if form.is_valid():
            form.save()
            messages.success(request, "Successfully updated lead")
            return redirect('leads_list')
    else:
        form = AddLeadForm(instance=lead)
    return render(request, 'lead/update_lead.html', {'form':form})

@login_required
def convert_to_client(request, pk):
    lead = get_object_or_404(Lead, created_by=request.user, pk=pk)
    acc = get_object_or_404(Account, user=request.user)
    lead.team = acc.team
    client = Client.objects.create(name=lead.name, email=lead.email, description=lead.description, team=lead.team, created_by=request.user)
    lead.converted_to_client = True
    lead.save()
    messages.success(request, "Lead converted to client")
    return redirect('leads_list')

@login_required
def contact_lead(request, pk):
    lead = get_object_or_404(Lead, created_by=request.user, pk=pk)
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            contact = form.save(commit=False)
            contact.subject = request.POST['subject']
            contact.email = lead.email
            contact.content = request.POST['content']
            contact.save()
            send_mail(
                contact.subject,
                contact.content,
                'settings.EMAIL_HOST_USER',
                [contact.email],
                fail_silently=False
            )
    else:
        form = ContactForm()
    return render(request, 'lead/contact_lead.html', {'form':form})

lead/templates/lead/add_lead.html
{% extends "home/base.html" %}

{% block content %}

<br><br>
<div class="col-md-6 offset-md-3">
  <h1>Add lead</h1>
  <form method="POST" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <br>
    <button type="submit" class="btn btn-secondary">Add lead</button>
  </form>
</div>
{% endblock %}

lead/templates/lead/contact_lead.html
{% extends "home/base.html" %}

{% block content %}

<br><br>
<div class="col-md-6 offset-md-3">
  <form method="POST" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <br>
    <button type="submit" class="btn btn-secondary">Send</button>
  </form>
</div>
{% endblock %}

lead/templates/lead/leads_list.html
{% extends "home/base.html" %}

{% block content %}

<div>
    <table class="table table-hover table-bordered">
        <thead class="table-dark">
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Priority</th>
            <th scope="col">Status</th>
            
          </tr>
        </thead>
        <tbody>
            {% for lead in leads %}
              <tr>
                <td><a href="{% url 'view_lead' lead.id %}">{{ lead.name }}</a></td>
                <td>{{ lead.get_priority_display }}</td>
                <td>{{ lead.get_status_display }}</td>
              </tr>
            {% endfor %}
        </tbody>
      </table>
    <button class="btn btn-secondary"><a class="nav-link" href="{% url 'add_lead' %}">Add lead</a></button>
</li>
</div>
{% endblock %}

lead/templates/lead/update_lead.html
{% extends "home/base.html" %}

{% block content %}

<br><br>
<div class="col-md-6 offset-md-3">
  <h1>Update lead</h1>
  <form method="POST" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <br>
    <button type="submit" class="btn btn-secondary">Update lead</button>
  </form>
</div>
{% endblock %}

lead/templates/lead/view_lead.html
{% extends 'home/base.html' %}

{% block content %}
<br><br>
<div class="col-md-6 offset-md-3">
    <div class="card">
        <div class="card-header">
           <strong>{{ lead.name }}</strong>
        </div>
        <div class="card-body">
            <p><strong>Name: </strong>{{ lead.name }}</p>
            <p><strong>Email: </strong>{{ lead.email }}</p>
            <p><strong>Description: </strong>{{ lead.description }}</p>
            <p><strong>Team: </strong>{{ lead.team }}</p>
            <p><strong>Priority: </strong>{{ lead.get_priority_display }}</p>
            <p><strong>Status: </strong>{{ lead.get_status_display }}</p>
            <p><strong>Created by: </strong>{{ lead.created_by }}</p>
            <p><strong>Created at: </strong>{{ lead.created_at }}</p>
            <p><strong>Modified at: </strong>{{ lead.modified_at }}</p>
        </div>
    </div>
    
    <br>
    <a href="{% url 'contact_lead' lead.id %}" class="btn btn-secondary">Contact</a>
    <a href="{% url 'update_lead' lead.id %}" class="btn btn-secondary">Update</a>
    <a href="{% url 'convert_to_client' lead.id %}" class="btn btn-success">Convert</a>
    <a href="{% url 'delete_lead' lead.id %}" class="btn btn-danger">Delete</a>
</div>
<br><br>

<div class="col-md-6 offset-md-3">
    <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-secondary">Comment</button>
    </form>
</div><br><hr><br>

<div class="col-md-6 offset-md-3">
    {% for comment in comments %}
    <div class="card">
        <div class="card-body">
            <button class="btn btn-light">{{ comment.created_by }}&nbsp;&nbsp;{{ comment.created_at }}</button>&nbsp;&nbsp;&nbsp;&nbsp;
            {{ comment.content }}
        </div>
    </div><br>
    {% endfor %}
</div>
    
{% endblock %}